[package]
name = "cursed_rust_for_max"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursed_macro = { path = "cursed_macro" }

[workspace]
members = ["cursed_macro"]
